# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenjuan', '0002_auto_20171213_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_t1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='list_t1s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1s', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='list_t3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t3', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='list_t3s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t3s', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='question_list',
        ),
    ]
