# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenjuan', '0003_auto_20171213_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=32)),
                ('stu_num', models.CharField(max_length=32)),
                ('stu_sex', models.CharField(max_length=8)),
                ('stu_class', models.CharField(max_length=32)),
                ('game1', models.CharField(max_length=8)),
                ('game2', models.CharField(max_length=8)),
                ('game3', models.CharField(max_length=8)),
                ('game4', models.CharField(max_length=8)),
                ('game5', models.CharField(max_length=8)),
                ('game6', models.CharField(max_length=8)),
                ('SH_self_m', models.CharField(max_length=8)),
                ('SH_allot_stu_a', models.CharField(max_length=32)),
                ('SH_allot_stu_a_m', models.CharField(max_length=8)),
                ('M_allot_stu_a', models.CharField(max_length=32)),
                ('M_allot_stu_a_M', models.CharField(max_length=8)),
                ('M_allot_stu_b', models.CharField(max_length=32)),
                ('M_allot_stu_b_M', models.CharField(max_length=8)),
                ('L_allot_stu_a', models.CharField(max_length=32)),
                ('L_allot_stu_a_M', models.CharField(max_length=8)),
                ('L_allot_stu_b', models.CharField(max_length=32)),
                ('L_allot_stu_b_M', models.CharField(max_length=8)),
                ('E_allot_stu_a', models.CharField(max_length=32)),
                ('E_allot_stu_a_M', models.CharField(max_length=8)),
                ('E_allot_stu_b', models.CharField(max_length=32)),
                ('E_allot_stu_b_M', models.CharField(max_length=8)),
            ],
        ),
    ]
