# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wenjuan', '0004_stu_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stu_record',
            old_name='E_allot_stu_a_M',
            new_name='E_allot_stu_a_m',
        ),
        migrations.RenameField(
            model_name='stu_record',
            old_name='E_allot_stu_b_M',
            new_name='E_allot_stu_b_m',
        ),
        migrations.RenameField(
            model_name='stu_record',
            old_name='L_allot_stu_a_M',
            new_name='L_allot_stu_a_m',
        ),
        migrations.RenameField(
            model_name='stu_record',
            old_name='L_allot_stu_b_M',
            new_name='L_allot_stu_b_m',
        ),
        migrations.RenameField(
            model_name='stu_record',
            old_name='M_allot_stu_a_M',
            new_name='M_allot_stu_a_m',
        ),
        migrations.RenameField(
            model_name='stu_record',
            old_name='M_allot_stu_b_M',
            new_name='M_allot_stu_b_m',
        ),
    ]
